//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Timezone { get; set; }
        public bool Open { get; set; }
        public bool Booking { get; set; }
        public bool Public { get; set; }
        public bool ThreeDSecure { get; set; }
        public int Order { get; set; }
        public string ManagerName { get; set; }
        public string ManagerDesc { get; set; }
        public string External_Id { get; set; }
        public Nullable<long> BookingSystemID { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> Circuit_Id { get; set; }
        public int DayStart { get; set; }
        public Nullable<bool> GiftStore { get; set; }
        public string SecondExternal_Id { get; set; }
        public bool IsPaymentWithGiftCardEnabled { get; set; }
        public bool IsLoyaltyEarnPointsEnabled { get; set; }
        public string TicketingUrl { get; set; }
        public bool isActive { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual CinemaAddress CinemaAddress { get; set; }
        public virtual Circuit Circuit { get; set; }
    }
}
