//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circuit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circuit()
        {
            this.Cinemas = new HashSet<Cinema>();
            this.FilmReleaseRules = new HashSet<FilmReleaseRule>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string BaseURI { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Open { get; set; }
        public bool Public { get; set; }
        public long HeadOfficeID { get; set; }
        public long CountryID { get; set; }
        public long ContactID { get; set; }
        public long MapPointID { get; set; }
        public Nullable<bool> UseLoyalty { get; set; }
        public Nullable<int> OrderTimeoutSeconds { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cinema> Cinemas { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
        public virtual HeadOffice HeadOffice { get; set; }
        public virtual MapPoint MapPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmReleaseRule> FilmReleaseRules { get; set; }
    }
}
