//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmReleaseRule
    {
        public long CircuitId { get; set; }
        public int FilmReleaseTypeId { get; set; }
        public Nullable<int> OpeningDate { get; set; }
        public Nullable<int> DateOfFirstSession { get; set; }
        public Nullable<int> DateOfLastSession { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public Nullable<bool> ComingSoon { get; set; }
        public Nullable<int> ComingSoonAttribute { get; set; }
        public Nullable<bool> ComingSoonByCinema { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Circuit Circuit { get; set; }
    }
}
