//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePermission
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int ModuleId { get; set; }
        public short PermissionId { get; set; }
    
        public virtual PermissionType PermissionType { get; set; }
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}
