//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderValueMetaData
    {
        public int Id { get; set; }
        public long ProviderValueId { get; set; }
        public string KeyProvider { get; set; }
        public string ValueProvider { get; set; }
        public int ModeId { get; set; }
    
        public virtual ProviderValue ProviderValue { get; set; }
    }
}
