//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderConfiguration
    {
        public long Id { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Action { get; set; }
        public string UrlAction { get; set; }
        public string Format { get; set; }
        public string Method { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
