//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachDigital.Administration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderValue()
        {
            this.ProviderValueMetaDatas = new HashSet<ProviderValueMetaData>();
        }
    
        public long Id { get; set; }
        public int ProviderId { get; set; }
        public int ModeId { get; set; }
        public Nullable<long> CircuitId { get; set; }
        public Nullable<long> CinemaId { get; set; }
        public string ProviderSetUpName { get; set; }
        public string ServiceName { get; set; }
        public string ProviderUrl { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ClientID { get; set; }
        public string WorkStationCode { get; set; }
        public string ClientClass { get; set; }
        public bool PerformPayment { get; set; }
        public string TemplatePrintStream { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderValueMetaData> ProviderValueMetaDatas { get; set; }
    }
}
